### PR TITLE
Enable `script-security` tests again

### PR DESCRIPTION
**Pull request by jglick**
Reverting #1444 since these should pass ~as soon as https://github.com/jenkinsci/script-security-plugin/pull/549 is deployed~ now that it is deployed.

Fixes https://github.com/jenkinsci/acceptance-test-harness/pull/1463

### CODE REVIEW

**Comment by jglick** [comment]
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1463/2/testReport/plugins/GroovyPluginTest/latest_linux_jdk21_firefox_split9___run_system_groovy_from_file/ :eyes: 

```
…	WARNING	o.k.s.HttpResponseRenderer$Default#handleJavaScriptProxyMethodCall: call to /$stapler/bound/…/approveSignature failed
java.lang.IllegalStateException: Expected 1 instance of org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist but got 2
	at hudson.ExtensionList.lookupSingleton(ExtensionList.java:457)
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist.configurationChanged(ScriptApproval.java:974)
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.reconfigure(ScriptApproval.java:1135)
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.approveSignature(ScriptApproval.java:1145)
```

**Comment by jglick** [comment]
Core bug? Locally

```groovy
[
    org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist,
    org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.ProxyWhitelist,
    org.jenkinsci.plugins.scriptsecurity.sandbox.Whitelist
].each {c ->
  println "$c: ${ExtensionList.lookup(c)}"
}; null
```

⇒

```
class org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist: [org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist@2a5adf3f[org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.AclAwareWhitelist@761fbf66], org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist@2a5adf3f[org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.AclAwareWhitelist@761fbf66]]
class org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.ProxyWhitelist: [org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist@2a5adf3f[org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.AclAwareWhitelist@761fbf66]]
class org.jenkinsci.plugins.scriptsecurity.sandbox.Whitelist: [org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.AnnotatedWhitelist@79647c59, org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist@3b3da89b, org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval$ApprovedWhitelist@2a5adf3f[org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.AclAwareWhitelist@761fbf66]]
```

Note that the `ApprovedWhitelist` appears twice when looked up under itself, but not when lookup up under supertypes. And I suppose this only happens when `script-security` is dynamically installed. Also https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1463/2/testReport/plugins/GroovyPluginTest/lts_linux_jdk11_firefox_split9___run_system_groovy_from_file/ passed. As did https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1463/2/testReport/plugins/ScriptSecurityPluginTest/latest_linux_jdk21_firefox_split8___signatureNeedsApproval/ which uses the same idiom https://github.com/jenkinsci/acceptance-test-harness/blob/29e61b9360280eb156282216af2184d6330bd792/src/test/java/plugins/ScriptSecurityPluginTest.java#L124-L126

**Comment by jglick** [comment]
I get the same error locally from `ScriptSecurityPluginTest.signatureNeedsApproval` so I suppose it is timing-sensitive.

**Review by timja — APPROVED** [review]
thanks!

**Pull request merged**
