### PR TITLE
[JENKINS-33730] More ATH tweaks for Jenkins 2.0

### PR DESCRIPTION
**Pull request by tfennelly**
Attn @olivergondza These should fix the scrolling issues + the missing plugin deps. I'm doing another local run of the tests here, so hopefully we are getting closer.

The original `scroller.js` just did not work as it was. `scrollIntoView` does not seem to be reliable (nor does `scrollBy`).

### CODE REVIEW

**Comment by olivergondza** [comment]
There seems to be a bug in detached plugins extraction:
```
run_on_a_particular_offline_slave(plugins.NodeLabelParameterPluginTest)  Time elapsed: 4.783 sec  <<< ERROR!
java.io.IOException: null
	at org.jenkinsci.test.acceptance.controller.LocalController.populateJenkinsHome(LocalController.java:184)
	at org.jenkinsci.test.acceptance.controller.JenkinsController.start(JenkinsController.java:94)
	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1$2$1.evaluate(JenkinsAcceptanceTestRule.java:164)
	at org.jenkinsci.test.acceptance.junit.FilterRule$1.evaluate(FilterRule.java:63)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:60)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.NullPointerException: null
	at org.jenkinsci.test.acceptance.controller.LocalController.installDetachedPlugins(LocalController.java:202)
	at org.jenkinsci.test.acceptance.controller.LocalController.populateJenkinsHome(LocalController.java:182)
	at org.jenkinsci.test.acceptance.controller.JenkinsController.start(JenkinsController.java:94)
	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1$2$1.evaluate(JenkinsAcceptanceTestRule.java:164)
	at org.jenkinsci.test.acceptance.junit.FilterRule$1.evaluate(FilterRule.java:63)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:60)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

```

**Comment by tfennelly** [comment]
There's still an issue with the tool installation. It's still trying to do it on the system config page (instead of the tool config).

**Comment by olivergondza** [comment]
LGTM, go ahead with the merge once you like the build result.

**Comment by daniel-beck** [comment]
https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness-stable/650/
Timed out.

**Comment by tfennelly** [comment]
I ran locally and we're now down to [14 errors and 5 warnings](https://gist.github.com/tfennelly/fe3c83c0f376ba31f0960d617173aeee). My local run against 1.x (master) gave me 11 errors and 3 failures, we we're nearly there.

The new remaining errors do not look serious. I'll analyse them on Monday.

@olivergondza Oliver ... do you want to merge this?

**Pull request merged**
