### PR TITLE
[JENKINS-30304] Removing workaround

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-30304](https://issues.jenkins-ci.org/browse/JENKINS-30304)

upstream https://github.com/jenkinsci/jenkins/pull/1908

@reviewbybees & @uhafner

### CODE REVIEW

**Comment by uhafner** [comment]
Until a fix for JENKINS-30304 is part of latest *and* lts core this test will fail. So shouldn't we keep the todo tag (or this PR) until your fix is part of lts core? 

I (or you) can create a new test for analysis-collector plug-in (based on this test) that has a @since annotation with the core version that contains the fix.

**Comment by recena** [comment]
@uhafner :+1:

**Comment by recena** [comment]
@uhafner https://github.com/jenkinsci/jenkins/pull/1908 was merged.

**Comment by recena** [comment]
@uhafner ping.

**Comment by uhafner** [comment]
I will get back to this during christmas break...

**Comment by recena** [comment]
@uhafner Perfect!

**Comment by uhafner** [comment]
Obsolete (See https://github.com/jenkinsci/acceptance-test-harness/commit/9a50640c808039f7a26e20ea5fdeae68712292e2)

**Pull request closed without merging**
