### PR TITLE
[JENKINS-26942] Update acceptance test to use stashes

### PR DESCRIPTION
**Pull request by jglick**
On hold until https://github.com/jenkinsci/workflow-plugin/pull/186 is merged and released.

@reviewbybees

### CODE REVIEW

**Comment by olivergondza** [comment]
Btw, it is possible to require updated version of plugin only for the one test that really needs it (and keep the rest testable with older version).

**Comment by oleg-nenashev** [comment]
Cannot be merge till the workflow-aggregator release. I would also prefer per-method declarations, because such implementation increases the test coverage.

**Comment by jglick** [comment]
Looked at `WithPlugins.RuleImpl.apply` and it was unclear whether a plugin version in a method annotation would properly *override* that in a class annotation, so am instead trying to just replace the class annotation.

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by stephenc** [comment]
:bee: from the :sunglasses: on :horse_racing:

**Pull request merged**
