### PR TITLE
tests: Test jenkinsci/jenkins 6687

### PR DESCRIPTION
**Pull request by NotMyFault**
https://github.com/jenkinsci/jenkins/pull/6687

### CODE REVIEW

**Comment by janfaracik** [comment]
Looks like the failures are happening here too - https://github.com/jenkinsci/acceptance-test-harness/pull/759/checks?check_run_id=7019662220

**Comment by NotMyFault** [comment]
> Looks like the failures are happening here too - https://github.com/jenkinsci/acceptance-test-harness/pull/759/checks?check_run_id=7019662220
> 
> Edit:
> 
> Opened a fix here #795

Looks all good so far but https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-794/3/testReport/junit/core/InstallWizardTest/java_11_jenkins_latest_split4___wizardInstallSuggestedTest/

Looks to be the same failure like on the initial run of this PR.

**Comment by timja** [comment]
Also failing over here:
https://github.com/jenkinsci/acceptance-test-harness/pull/759/checks?check_run_id=7040468217

**Comment by janfaracik** [comment]
> Also failing over here:
> https://github.com/jenkinsci/acceptance-test-harness/pull/759/checks?check_run_id=7040468217

Seems like the test is failing as it's trying to hit `.install-done` but the only available button is `.install-done-restart`. Not too sure what's changed but it seems like a restart is now required.

**Comment by timja** [comment]
> Seems like the test is failing as it's trying to hit .install-done but the only available button is .install-done-restart. Not too sure what's changed but it seems like a restart is now required.

We want to avoid that normally as it will slow the tests down a lot, it'll be something to do with detached plugins probably.

**Comment by NotMyFault** [comment]
If that specific test failure is only applicable if a run is executed more than one time, I'm fine if we dismiss it on this specific PR test and handle it as general issue. No need to block the core PR longer than needed imo.

**Pull request closed without merging**
