### PR TITLE
More Jenkins 2.0 test fixes

### PR DESCRIPTION
**Pull request by tfennelly**
Attn @olivergondza 

The only test failure difference from my initial run against master is `SubversionPluginTest.clean_checkout:199`:

```
 SubversionPluginTest.clean_checkout:199 
Expected: Build result SUCCESS
     but: was FAILURE. Console output:
Started by user anonymous
Building in workspace /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace
Cleaning up /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace/.
Deleting /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace/unversioned.txt
Updating http://127.0.0.1:32883/svn at revision '2016-04-01T20:13:53.243 +0100'
At revision 2

No changes for http://127.0.0.1:32883/svn since the previous build
[workspace] $ /bin/sh -xe /tmp/hudson3162125481586565868.sh
+ echo test
[workspace] $ /bin/sh -xe /tmp/hudson8389200259849604126.sh
+ test -f unversioned.txt
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

The `test` command is failing. Where's the bang gone when executing?

### CODE REVIEW

**Comment by olivergondza** [comment]
Huh, that looks like a typo in the command. Should be `test ! -f unversioned.txt`.

The funny thing is the `!` makes it correct (when using bash). From the man page: "If the reserved word ! precedes a pipeline, the exit status of that pipeline is the logical negation of the exit status as described above".

**Comment by tfennelly** [comment]
`! test -f unversioned.txt` is what's configured in the build step on the job and it works fine if I run it from the command line myself. It just seems to be getting dropped from the generated script file. `test -f unversioned.txt` is all that's printed in the log, which will exit `1` and fail the build.

**Comment by olivergondza** [comment]
I can not confirm that. Locally, I gets configured correctly. It is just bash not printing it with `set -x` on. See: `set -x; ! false; echo $?`

**Comment by olivergondza** [comment]
I have used the less surprising form https://github.com/jenkinsci/acceptance-test-harness/commit/85ee4f94ffdd3a1ccc4a844672c626c62d89e282. Though, I do not see why is this failing for you.

**Comment by olivergondza** [comment]
This PR looks good to me BTW.

**Pull request merged**
