### PR TITLE
Fixing WorkflowPluginTest for 1.14

### PR DESCRIPTION
**Pull request by jglick**
@reviewbybees esp. @tfennelly

### CODE REVIEW

**Comment by jglick** [comment]
Note that the tests failed because at the time the UC had only 1.13.

**Comment by jglick** [comment]
But without this PR, new test runs [will fail](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness/1585/testReport/plugins/WorkflowPluginTest/helloWorld/).

**Comment by kwhetstone** [comment]
:bee: makes sense

**Comment by andresrc** [comment]
:bee:

**Comment by svanoort** [comment]
:bee: belatedly

**Pull request merged**
