### PR TITLE
[JENKINS-26192] Demonstrating @Grab support in a realistic class loader environment

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/9.

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
:bee:

**Comment by abayer** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
This was not supposed to be merged before `workflow-cps-global-lib@2.3` was actually released! Apparently `@WithPlugins` does not work properly: the test should get skipped unless and until the specified version of the plugin is available.

**Comment by olivergondza** [comment]
Right, the annotation is not ready for that: [JENKINS-38015](https://issues.jenkins-ci.org/browse/JENKINS-38015)

**Pull request merged**
