### PR TITLE
the WebDriver may be wrapped so we also need to unwrap it

### PR DESCRIPTION
**Pull request by jtnord**
The WebDriver may be wrapped or unwrapped so we need to unwarp it to get
the underlying driver to see if that is a RemoteWebDriver to configure
the FileDetector

amends #884

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by jtnord** [comment]
Build failure is real 

```Setting the file detector only works on remote webdriver instances obtained via RemoteWebDriver```

**Review by NotMyFault — APPROVED** [review]

**Comment by jtnord** [comment]
this appears to be a regression in the weekly at some point.

The dialog is not removed correctly - firstly the buttons are remoed, then the background styling and sometime later the fields etc.  this is visibly slow and causing screen redraw, whereas on the LTS the button and dialog seem to disappear "as one"

**Comment by jtnord** [comment]
`2.358` is ok  `2.359` fails

**Comment by jtnord** [comment]
`plugins.SshSlavesPluginTest.connectWithKey` is flaky (more so with recent cores) but I believe this is now well and truly fixed...

**Review by timja — APPROVED** [review]

**Pull request merged**
