### PR TITLE
UI for adding user changed.

### PR DESCRIPTION
**Pull request by lvotypko**
UI for adding user in matrix authentication plugin has changed. This fix should work for Jenkins version 2.60+ and plugin version 2.3+. I do not think that we need backward compatibility for previous versions of plugins or Jenkins (I do not like to have a lot of if/else for due to jenkins/plugin version), anyone with different opinion?

### CODE REVIEW

**Comment by lvotypko** [comment]
there are changes in login page, so first wait for pull request https://github.com/jenkinsci/acceptance-test-harness/pull/447

**Comment by lvotypko** [comment]
after merging master with last pull request (fixing tests for new UI of login), the MatrixAuthPluginTest is finally passing.

**Comment by daniel-beck** [comment]
I'm sorry for having missed this. Thanks for taking care of it!

**Comment by romainverduci** [comment]
@lvotypko Some tests will break (and are actually breaking) if using a version < 2.3 of matrix auth plugin. I'm not sure forcing the upgrade of a plugin to make a test green is a good motivation. What's your opinion on that ?

**Pull request merged**
