### PR TITLE
use custom DNS in the ath container to enable HAR recording

### LINKED ISSUE #1165: HAR recording on ci.jenkins.io does not record interaction with Jenkins
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1159/3/testReport/junit/plugins/WorkflowPluginTest/lts_linux_jdk11_firefox_split2___parallelTests/

### Reproduction steps

1. have a flaky / failing test
2. on the build in ci.jenkins.io open the test report and download the HAR for the test
3. open the HAR

### Expected Results

the HAR contains all interactions with the system under test

### Actual Results

there are no interactions recorded with Jenkins

### Anything else?

Jenkins is running on `127.0.0.1` and as such by default firefox will not use the proxy - so the HAR is useless

### PR DESCRIPTION
**Pull request by jtnord**
Firefox will not use a proxy for 127.0.01

can be worked around by using a custom DNS entry

fixes #1165

### Testing done

built the container image locally and introduced a failing test into the source
ran the test `run.sh firefox latest -DforkCount=1 -Dmaven.test.failure.ignore=true -B -Dtest=FailingTest -DElasticTime.factor=10` inside the container and inspected the resulting har

image

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jtnord** [comment]
Alternative to an external service is to ensure that `docker run` is called with `--add-host` but that would require all users (and ci) to update their usage.

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Flaked in at least https://github.com/jenkinsci/jenkins/pull/8340/checks?check_run_id=15831626321 FYI

**Comment by timja** [comment]
and https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-8363/2/tests/

**Comment by timja** [comment]
reverted, maybe we should add a localhost.jenkins.io domain?

**Comment by jtnord** [comment]
> localhost.jenkins.io

I recall somewhere in the depths of my memory that it is discouraged to add a localhost to a domain like that as it can lead to some subtle security issues (which we would not care about for sslip.io but would for jenkins.io).

will file something updated.

**Comment by timja** [comment]
> > localhost.jenkins.io
> 
> I recall somewhere in the depths of my memory that it is discouraged to add a localhost to a domain like that as it can lead to some subtle security issues (which we would not care about for sslip.io but would for jenkins.io).
> 
> will file something updated.

I'm not aware of anything that could cause an issue for that, but sure.

**Pull request merged**
