### PR TITLE
[JENKINS-39716] adapt docker tests execution when ATH itself runs as docker container

### PR DESCRIPTION
**Pull request by mafraba**
[JENKINS-39716](https://issues.jenkins-ci.org/browse/JENKINS-39716)

Support running ATH as docker container. Connect to docker fixtures through docker IPs instead of using host port-mappings.

For the moment, an environment variable SHARED_DOCKER_SERVICE is used to select this behaviour. Maybe in the future try to detect the situation automatically.

@reviewbybees

### CODE REVIEW

**Comment by armfergom** [comment]
LGTM 🐝

**Comment by olivergondza** [comment]
Please drop a line about it into the docs.

**Comment by mafraba** [comment]
Little paragraph added in FIXTURES.md

**Comment by mafraba** [comment]
@olivergondza does that doc look good?

**Comment by olivergondza** [comment]
Yes, thanks.

**Pull request merged**
