### PR TITLE
[FIXED JENKINS-31060] Removing AntPluginTest.locallyInstalledAnt()

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-31060](https://issues.jenkins-ci.org/browse/JENKINS-31060)

I just don't see the point of this test in the first place - it's too
hard to control for environment to be worth keeping around.

cc @reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
ping? Thoughts?

**Comment by jglick** [comment]
:bee:, I also see little point in this test.

**Comment by kwhetstone** [comment]
:bee: Especially if it helps stability.

**Comment by abayer** [comment]
@reviewbybees done

**Pull request merged**
