### PR TITLE
[JENKINS-40502] Create PO for Authorize project plugin and a test.

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-40502](https://issues.jenkins-ci.org/browse/JENKINS-40502)

- Create PO for Authorize project plugin.
- Make GlobalSecurity config to be able to add it.
- Create test.

@reviewbybees

### CODE REVIEW

**Comment by mafraba** [comment]
🐝

**Comment by armfergom** [comment]
Code looks good to me, although I cannot see a successful run of the test. The build is failing.

**Comment by varyvol** [comment]
@armfergom I think it was a failure when killing the VNC session. I have closed/reopened so that the tests are launched again.

**Comment by varyvol** [comment]
@olivergondza I think this one is ready. Could you please merge it?

**Pull request merged**
