### PR TITLE
[JENKINS-40479] Control rare race condition in WithCredentials annotation

### PR DESCRIPTION
**Pull request by mafraba**
[JENKINS-40479](https://issues.jenkins-ci.org/browse/JENKINS-40479)

Control race condition when preparing credentials with `@WithCredentials` annotation.

@reviewbybees

### CODE REVIEW

**Comment by varyvol** [comment]
🐝

**Comment by recena** [comment]
🐝

**Comment by mafraba** [comment]
@reviewbybees done

**Comment by mafraba** [comment]
Refactored into page object since the same issue might potentially affect other tests.

**Comment by varyvol** [comment]
🐝

**Comment by mafraba** [comment]
@reviewbybees done

**Pull request merged**
