### PR TITLE
Fix toggle in JUnit build results.

### PR DESCRIPTION
**Pull request by andresrc**
@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝  since I've been talking with @andresrc about it.

**Comment by olivergondza** [comment]
This reflect a change in a plugin and fix like this is going to break the tests for the old version. Given the cosmetic change that broke this, we should imho rewrite the assert to visit the test page and get the message from there to be less fragile.

**Comment by andresrc** [comment]
@olivergondza agree, will fix, thanks!

**Comment by recena** [comment]
@olivergondza I agree, we can use another selector less fragile. Other option would be to set the minimum version of JUnit where the change was done.

**Comment by armfergom** [comment]
LGTM 🐝

**Comment by abayer** [comment]
:bee:, merging.

**Pull request merged**
