### PR TITLE
[JENKINS-38974] Required version can be null

### PR DESCRIPTION
**Pull request by andresrc**
Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/199

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
:bee:

**Comment by mafraba** [comment]
🐝

**Comment by bpedersen2** [comment]
Was the bug reference correct?  [JENKINS-38974] looks like it really is "Comment Added event crashes with NullPointerException"
[JENKINS-38794] seems to be the right reference

**Comment by andresrc** [comment]
@bpedersen2 exactly, is a typo. Thanks!

**Pull request merged**
