### PR TITLE
update assertj from 3.11.1 to 3.12.2

### PR DESCRIPTION
**Pull request by based2**

### CODE REVIEW

**Comment by olivergondza** [comment]
@based2, I see a lot of PRs updating one dependency at a time. What is the motivation here?

**Comment by oleg-nenashev** [comment]
See https://github.com/jenkinsci/sshd-module/pull/30 for the discussion with @based2 w.r.t this topic

**Comment by based2** [comment]
to be able to pass the tests on each changes, and to have better historic of the changes

**Comment by olivergondza** [comment]
@based2, my question was what is the motivation for bumping the versions to begin with.

**Comment by olivergondza** [comment]
Am closing this PR. Let's bump the versions where the is a need to.

**Pull request closed without merging**
