### PR TITLE
Use older 108 version of firefox in ath-container

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
110 (current one available in ppa) seems to have some issues with Selenium making the existing code not work anymore

~So to validate is the firefox version I am using here firefox esr 108, if that solves problems I will rewrite to use the standard firefox instead, sadly 108 version is not on the ppa repository anymore, that is why for this tests I am using esr~

The last known good version was 108.0.2, which is now installed, and fixed,  in the docker image. Basically I copied and adapted the installation procedure from the selenium docker images.

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timja** [comment]
Nice looks like that was the issue. Tests are _generally_ passing now.

**Comment by timja** [comment]
2 plugins are failing

External workspace manager fixed here:
https://github.com/jenkinsci/external-workspace-manager-plugin/pull/77

Ownership plugin needs checking, (that ones due to core changes)

**Comment by timja** [comment]
@raul-arabaolaza is there anything else you wanted to do on this PR?

**Comment by raul-arabaolaza** [comment]
@timja Yes, now that it is confirmed it works I plan to do a proper firefox 108 installation instead of using esr and rename the firefox executable. I will do it in around 24 hours, then I will be very happy to have this merged if possible so I can jump to fix the docker based tests

**Comment by raul-arabaolaza** [comment]
@timja I consider this code complete, if it works I am all in for merge

**Review by rsandell — APPROVED** [review]

**Review by jtnord — APPROVED** [review]
Seems ok

if we need somethign like this for a longer term workaround - did you consider using a multi-stage docker build and copying the binaries from `selenium/standalone-firefox` instead?

That way we should get dependabot to proprose updates that can be tested and also ensure that the firefox and geckodriver are kept in sync.

**Review by BorisYaoA — APPROVED** [review]

**Pull request merged**
