### PR TITLE
Do not assume that `forkCount` is an integer

### PR DESCRIPTION
**Pull request by jglick**
`warnings-ng` failed in PCT with

```
java.lang.NumberFormatException: For input string: ".75C"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.jenkinsci.test.acceptance.utils.ElasticTime.<init>(ElasticTime.java:48)
	at org.jenkinsci.test.acceptance.utils.IOUtil.<clinit>(IOUtil.java:39)
	at …
```

See https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkCount

> When terminated with "C", the number part is multiplied with the number of CPU cores. Floating point value are only accepted together with "C".

### CODE REVIEW

**Comment by jglick** [comment]
@uhafner I am afraid it looks like https://github.com/jenkinsci/warnings-ng-plugin/pull/1327 needs to be amended with something picking up this fix.

**Review by basil — APPROVED** [review]

**Comment by jglick** [comment]
Test failures are #877 I guess.

**Review by NotMyFault — APPROVED** [review]

**Comment by jglick** [comment]
For purposes of `warnings-ng` PCT we would need
* this to be merged
* a new ATH release to be cut
* `warnings-ng-plugin` to update to that ATH dep version
* a new `warnings-ng` release

The workaround is just to expect and ignore failures of `io.jenkins.plugins.analysis.warnings.SmokeTests`.

**Comment by NotMyFault** [comment]
> For purposes of `warnings-ng` PCT we would need
> 
> * this to be merged
> * a new ATH release to be cut
> * `warnings-ng-plugin` to update to that ATH dep version
> * a new `warnings-ng` release
> 
> The workaround is just to expect and ignore failures of `io.jenkins.plugins.analysis.warnings.SmokeTests`.

Consider 1 and 2 as done.

**Comment by jglick** [comment]
@NotMyFault how did you release specifically? https://repo.jenkins-ci.org/public/org/jenkins-ci/acceptance-test-harness/ does not have 1.118.

We need to set up JEP-229 here IMO.

**Comment by jglick** [comment]
Maybe the `release:perform` failed? If so, you can simply rerun it if you have not cleaned your checkout (it will use the `release.properties`).

**Comment by jglick** [comment]
(In general with `maven-release-plugin` you just need to throw your hands up in the air, forget about the broken release, and try with a new release version.)

**Comment by NotMyFault** [comment]
> if you have not cleaned your checkout

Unfortunately I did 😦 

No idea what went wrong this time, just filed https://github.com/jenkins-infra/repository-permissions-updater/pull/2714 to utilize CD here too 👏🏻

**Comment by jglick** [comment]
> Unfortunately I did

Just cut 1.119 I guess.

**Comment by jtnord** [comment]
git checkout the tag.. `mvn deploy -DskipTests`  will do that now
I will do that now

**Comment by basil** [comment]
BTW I typically cut releases with `mvn -Darguments=-DskipTests release:prepare release:perform` to avoid having to wait for the tests. Of course before doing that I verify that the latest CI run was passing. :smile:

**Comment by jtnord** [comment]
> BTW I typically cut releases with `mvn -Darguments=-DskipTests release:prepare release:perform` to avoid having to wait for the tests. Of course before doing that I verify that the latest CI run was passing. 😄

ftr not needed here due to https://github.com/jenkinsci/acceptance-test-harness/blob/b1ebe8c9e949969f9835ea5951600d6befbe0f92/pom.xml#L550

**Comment by jtnord** [comment]
https://repo.jenkins-ci.org/releases/org/jenkins-ci/acceptance-test-harness/1.118/

**Pull request merged**
