### PR TITLE
Make plugin overriding work when uploadPlugins=false

### PR DESCRIPTION
**Pull request by andresrc**
As described [here|https://github.com/jenkinsci/acceptance-test-harness/blob/master/docs/SUT-VERSIONS.md] a custom plugin version can be provided by setting the `<id>.jpi` environment variable to the path of the custom version.

However, these mechanism does not work when the `uploadPlugins` config option is set, and this PR fixes that.

### CODE REVIEW

**Comment by recampbell** [comment]
🐝

**Comment by olivergondza** [comment]
How do you intend to implement that? Meaning how can UI install/update be used to deploy plugin snapshot builds from by `~/.m2/repository`? My current thinking is to do upload in case there is some overriding, UI install otherwise.

**Comment by jglick** [comment]
I am guessing this is now obsolete. After #379, is there still any problem you see?

**Comment by olivergondza** [comment]
Agreed.

**Pull request closed without merging**
