### PR TITLE
fix WebDriverException on non-X11 platforms

### PR DESCRIPTION
**Pull request by varmenise**

### CODE REVIEW

**Comment by varmenise** [comment]
@olivergondza is this commit https://github.com/jenkinsci/acceptance-test-harness/commit/87b3e04252e723ad026db5dd8265726fbafa7d0f to address the same as this PR? In such case I ll just close this

**Comment by amuniz** [comment]
:bee:

**Comment by andresrc** [comment]
:bee:

**Comment by jglick** [comment]
:bee:

**Pull request merged**
