### PR TITLE
[JENKINS-36392] Fix ArtifactoryPluginTest#check_config_is_persisted

### PR DESCRIPTION
**Pull request by mafraba**
Solves [Issue JENKINS-36392](https://issues.jenkins-ci.org/browse/JENKINS-36392).

It seems that the expected message was incorrect/outdated. Fixed to the string that Jenkins actually returns.

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝

**Comment by abayer** [comment]
Failed against 1.651.2 for me -

```
14:51:12 check_config_is_persisted(plugins.ArtifactoryPluginTest)  Time elapsed: 140.072 sec  <<< ERROR!
14:51:12 org.openqa.selenium.TimeoutException: Timed out after 10 seconds: Text matching \QError occurred while requesting version information: Connection refused\E. was "http://127.0.0.1:63481/configure"
14:51:12 " Jenkins\nconfiguration\n New Item\n People\n Build History\n Manage Jenkins\n Credentials\nBuild Queue\nNo builds in the queue.\nBuild Executor Status\n1 Idle\n2 Idle\n  Home directory /root/workspace/workspace/test-jobs/abayer-stuff/abayer-cje-oss-ath-test-docker/jenkins372733413022764416home\n Advanced...\n  System Message\n[Plain text] Preview \n  # of executors\n  Labels\n  Usage\nUtilize this node as much as possible\nOnly build jobs with label restrictions matching this node\n  Quiet period\n  SCM checkout retry count\nRestrict project naming\nGlobal properties\nEnvironment variables\nTool Locations\nMaven Configuration\n  Default settings provider\nUse default maven settings\nSettings file in filesystem\nprovided settings.xml\n  Default global settings provider\nUse default maven global settings\nGlobal settings file on filesystem\nprovided global settings.xml\nJDK\n  JDK installations\nAdd JDK\nList of JDK installations on this system\nGit\n  Git installations\nGit\n  Name\n  Path to Git executable\nInstall automatically\nDelete Git\nAdd Git\ndescription\nGradle\n  Gradle installations\nAdd Gradle\nList of Gradle installations on this system\nAnt\n  Ant installations\nAdd Ant\nList of Ant installations on this system\nMaven\n  Maven installations\nAdd Maven\nList of Maven installations on this system\nIvy Project Configuration\n  Global ANT_OPTS\nMaven Project Configuration\n  Global MAVEN_OPTS\n  Local Maven Repository\nDefault (~/.m2/repository)\nLocal to the executor\nLocal to the workspace\nHelp make Jenkins better by sending anonymous usage statistics and crash reports to the Jenkins project.\nJenkins Location\n  Jenkins URL\n  System Admin e-mail address\nSSH Server\n  SSHD Port\nFixed :  Random Disable\nArtifactory\n  Enable Push to Bintray\n  Use the Credentials Plugin\n  Artifactory servers\nArtifactory\n  Server ID\nPlease set server ID\n  URL\nDefault Deployer Credentials\n  Username\n  Password\n Advanced...\n  Test Connection\nError occurred while requesting version information: Connection to http://localhost:4898 refused\nUse Different Resolver Credentials\n  Delete\nAdd\nList of Artifactory servers that projects will want to deploy artifacts and build info to\nCVS\n  Default Compression Level\nNone\n1\n2\n3 (Recommended)\n4\n5\n6\n7\n8\n9\n  Private Key Location\n  Private Key Password\n  Known Hosts Location\n  Authentication\nAdd\nSubversion\n  Subversion Workspace Version\n1.4\n1.5\n1.6 (svn:externals to file)\n1.7\n  Exclusion revprop name\nValidate repository URLs up to the first variable name\nUpdate default Subversion credentials cache after successful authentication\nShell\n  Shell executable\nIvy Build Trigger\n  Ivy Revision Matching Use extended revision matching to filter the project dependency graph\n  Ivy Settings\nAdd\nList of Ivy Settings\nE-mail Notification\n  SMTP server\n  Default user e-mail suffix\n Advanced...\nTest configuration by sending test e-mail\nSave\nApply\nHelp us localize this page\nPage generated: Jul 5, 2016 9:49:53 PM UTCREST APIJenkins ver. 1.651.2"
14:51:12 Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
14:51:12 System info: host: 'ip-10-216-229-216', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.8.0_40'
14:51:12 Driver info: driver.version: unknown
14:51:12 	at org.openqa.selenium.support.ui.FluentWait.timeoutException(FluentWait.java:292)
14:51:12 	at org.jenkinsci.test.acceptance.junit.Wait.timeoutException(Wait.java:143)
14:51:12 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:261)
14:51:12 	at org.jenkinsci.test.acceptance.junit.Wait.until(Wait.java:128)
14:51:12 	at org.jenkinsci.test.acceptance.junit.Wait.until(Wait.java:94)
14:51:12 	at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.waitFor(CapybaraPortingLayerImpl.java:163)
14:51:12 	at plugins.ArtifactoryPluginTest.check_config_is_persisted(ArtifactoryPluginTest.java:62)
```

So for the moment, :bug:

**Comment by mafraba** [comment]
I've been trying to track where the message itself is generated in the application, and it seems to come from the apache httpclient itself (followed [this track](https://github.com/JFrogDev/build-info/blob/master/build-info-extractor/src/main/java/org/jfrog/build/extractor/clientConfiguration/client/ArtifactoryBuildInfoClient.java#L300)). So I imagine different versions of this dependency can be the reason.

Anyway, the message is basically the same: "Connection refused", detailing the host or not. I think in both cases the test should pass, and now it does.

Please @abayer @recena review again. Thanks.

**Comment by abayer** [comment]
It's still inconsistent for me, but that's probably not worth blocking this, so :bee:

**Comment by mafraba** [comment]
By inconsistent you mean it's failing?

**Comment by abayer** [comment]
Sometimes it passes, sometimes it doesn't, can't figure out what's different. So this may not be the definitive final fix for this, but it's progress. =)

**Comment by mafraba** [comment]
This inconsistency doesn't happen to me working on Linux, but after your comment I've tried different environments and I have been able to experience it on Mac. In particular, the failure I have been receiving randomly was about not being able to install the artifactory plugin: `java.lang.IllegalArgumentException: artifactory plugin not installed`.

Anyway, the particular problem in the issue seems fixed and, as I said, in linux the suite always passes. It also passed in the CI run. So all in all I think this can be merged.

@reviewbybees done

**Pull request merged**
