### PR TITLE
Fix deploy plugin test

### PR DESCRIPTION
**Pull request by timja**
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1272/3/testReport/junit/plugins/DeployPluginTest/latest_linux_jdk17_firefox_split4___deploy_sample_webapp_to_tomcat10/attachments/docker-Tomcat10Container.build.log

Shows:
```

#7 [4/6] RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
#7 0.214 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#7 0.224 Executing: /tmp/apt-key-gpghome.ITWLNzmTeG/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
#7 60.53 gpg: keyserver receive failed: Connection timed out
#7 ERROR: process "/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5" did not complete successfully: exit code: 2
```

Lets try this, otherwise I think this is the key and can just add to repo:
https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x630239cc130e1a7fd81a27b140976eaf437d05b5

I can't build this locally as-is as the tomcat10 package isn't available on arm64, we could switch to the binary distribution though

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by timja** [comment]
Err this whole problem is caused by the moving of subnet for the agents.

@dduportal is there a reason outbound ports are limited to 80 and 443?

image

**Comment by timja** [comment]
Anyway this will do for now

**Comment by dduportal** [comment]
Thanks for the notification. Tracked in https://github.com/jenkins-infra/helpdesk/issues/3664.

**Comment by dduportal** [comment]
Btw: `Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).` we are also working on getting rid of this in different infra context. Appeared with Ubuntu Jammy (and I guess modern Debian such as bookworm).

**Comment by timja** [comment]
> Btw: `Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).` we are also working on getting rid of this in different infra context. Appeared with Ubuntu Jammy (and I guess modern Debian such as bookworm).

saw that, I would have fixed it but the container doesn't build on my machine (doesn't work on arm64) so a bit more involved unfortunately than a quick fix.

**Pull request merged**
