### PR TITLE
[JENKINS-35307] Discriminate Jenkins version for certain UI aspects when creating/copying jobs

### PR DESCRIPTION
**Pull request by mafraba**
Reopened [JENKINS-35307](https://issues.jenkins-ci.org/browse/JENKINS-35307) to make the test work for Jenkins `2.x` as well.

Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/112.

@reviewbybees esp @abayer @recena @tfennelly

### CODE REVIEW

**Comment by recena** [comment]
🐝  More clear.

**Comment by tfennelly** [comment]
🐝 LGTM, but I obviously @olivergondza needs to review it too.

**Comment by recena** [comment]
@tfennelly We have an important challenge in front of us because the ATH needs to be compatible with Jenkins `1.x` and `2.x` 😄

**Comment by mafraba** [comment]
@reviewbybees Done

**Pull request merged**
