### PR TITLE
[JENKINS-38029] Wait for Yes button before clicking

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
[JENKINS-38029](https://issues.jenkins-ci.org/browse/JENKINS-38029)

@reviewbybees

### CODE REVIEW

**Comment by varmenise** [comment]
🐝

**Comment by varmenise** [comment]
🐝

**Comment by andresrc** [comment]
:bee:

**Comment by svanoort** [comment]
🐝

**Comment by recena** [comment]
🐝

**Comment by raul-arabaolaza** [comment]
@reviewbybees done

**Comment by raul-arabaolaza** [comment]
Hey @olivergondza One quick merge here, please?

**Pull request merged**
