### PR TITLE
[JENKINS-46999] Update UI for changes in github-branch-source-2.2.0

### PR DESCRIPTION
**Pull request by fcojfernandez**
[JENKINS-46999](https://issues.jenkins-ci.org/browse/JENKINS-46999)

Update UI for changes in github-branch-source-2.2.0

@reviewbybees

### CODE REVIEW

**Comment by varyvol** [comment]
🐝

**Comment by recena** [comment]
Waiting for the results of the  PR builder...

**Comment by fcojfernandez** [comment]
@olivergondza after analyse the tests that have failed, none of them are related to the changes committed. Do you think you could merge this PR?

**Comment by fcojfernandez** [comment]
@olivergondza thanks!

**Pull request merged**
