### PR TITLE
[JENKINS-29922] Testing use of symbols in a realistic context

### PR DESCRIPTION
**Pull request by jglick**
Requires https://github.com/jenkinsci/junit-plugin/pull/53 to actually pass.

@reviewbybees esp. @kohsuke

### CODE REVIEW

**Comment by jglick** [comment]
Trying to get a release of `junit`, but currently blocked by Artifactory authentication problems.

**Comment by jglick** [comment]
@olivergondza you maintain this right?

**Comment by jglick** [comment]
Note that the modified tests [are being skipped](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness-stable/954/testReport/plugins/WorkflowPluginTest/), though Jenkins does not report the reason (bug in the `junit` plugin I suppose).

**Comment by olivergondza** [comment]
:+1:

**Comment by olivergondza** [comment]
> Note that the modified tests are being skipped, though Jenkins does not report the reason (bug in the junit plugin I suppose).

The JUnit XML reports merely note it was skipped without the reason - not sure something can be done about that). ATH put that reason on stderr (see [subversion results](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness-stable/954/testReport/plugins/SubversionPluginTest/poll_for_changes_excluded/)). I am unsure why those are skipped without any details.

**Comment by jglick** [comment]
Hmm,

```
Skipping linearFlow(plugins.WorkflowPluginTest)
org.junit.internal.AssumptionViolatedException: junit has version 1.15 but 1.18 was requested
	at org.jenkinsci.test.acceptance.po.PluginManager.installPlugins(PluginManager.java:199)
	at org.jenkinsci.test.acceptance.junit.WithPlugins$RuleImpl$1.doInstall(WithPlugins.java:141)
	at org.jenkinsci.test.acceptance.junit.WithPlugins$RuleImpl$1.installPlugins(WithPlugins.java:128)
```

I suspect that when the test ran, the update center had not yet been refreshed. [Build 950](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness-stable/950/testReport/plugins/WorkflowPluginTest/attachments/plugins.WorkflowPluginTest-output.txt) did pass, with `junit` 1.15. (1.18 is required when running against Jenkins 1.x.)

**Pull request merged**
