### PR TITLE
[JENKINS-39828] Ignore test if plugin cannot be updated through the UI

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-39828](https://issues.jenkins-ci.org/browse/JENKINS-39828)

@reviewbybees @andresrc @olivergondza

### CODE REVIEW

**Comment by mafraba** [comment]
🐝  looks good

**Comment by raul-arabaolaza** [comment]
LGTM :bee:

**Comment by olivergondza** [comment]
I presume this can happen in 2 cases: Requiring unreleased plugin version or using Jenkins version too old for the required plugin version. It makes sense to me.

**Comment by recena** [comment]
:bee:

**Comment by andresrc** [comment]
Yes, and those cases are more common when using `uploadPlugins=false`

**Comment by olivergondza** [comment]
Actually, I am not sure about this. *Using Jenkins version too old for the required plugin version* should show a warning there but should still be presented. I am afraid this will hide real problems when UI changes.

@andresrc, This can be triggered if and only if `uploadPlugins=false`.

**Comment by andresrc** [comment]
@olivergondza makes sense

**Comment by varyvol** [comment]
@olivergondza this only happens when uploadPlugins=false, as only then the private method tickPluginToInstall() is called.

**Pull request merged**
