### PR TITLE
[JENKINS-34690] Analysis collector ATH tests failing

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
[JENKINS-34690](https://issues.jenkins-ci.org/browse/JENKINS-34690)

I suspect is some very similar to [JENKINS-31738](https://issues.jenkins-ci.org/browse/JENKINS-31738), so I used the same approach.

@reviewbybees

### CODE REVIEW

**Comment by armfergom** [comment]
Nothing you can `waitFor` instead of using a plain sleep?

**Comment by raul-arabaolaza** [comment]
@armfergom Nothing that I can imagine, I need to give time to JS code to execute and update some values, not wait for some element to appear. But if you have any idea I would change the PR gladly, I am not fan of plain sleep

**Comment by raul-arabaolaza** [comment]
It has succesfully executed on CI, so no longer WIP

`Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,399.74 sec - in plugins.AnalysisCollectorPluginTest`

**Comment by recena** [comment]
🐝

**Comment by recena** [comment]
@olivergondza Thanks a lot!

**Pull request merged**
