### PR TITLE
Fix tests for cifs publisher

### PR DESCRIPTION
**Pull request by olivergondza**

### CODE REVIEW

**Comment by lvotypko** [comment]
I agree, due to problems with docker cp, see [1], it is better not to use it if it is not necessary. In this case it can be easy done another way.

[1] https://github.com/jenkinsci/docker-fixtures/pull/17

**Comment by olivergondza** [comment]
This is still a work in progress as this has uncovered what appears to be a real regression in the plugin.

**Comment by olivergondza** [comment]
Filing the discovered issue as https://issues.jenkins-ci.org/browse/JENKINS-51852

**Comment by olivergondza** [comment]
Their plugin version is fairly old...

**Pull request merged**
