### PR TITLE
Tests for Manage Jenkins renaming

### PR DESCRIPTION
**Pull request by janfaracik**
For https://github.com/jenkinsci/jenkins/pull/7661

### CODE REVIEW

**Comment by janfaracik** [comment]
Hey @timja, ran a couple of the failed tests locally and they seem to pass - am I doing something wrong in this PR?

**Comment by timja** [comment]
Requires this PR to be merged first:
https://github.com/jenkinsci/acceptance-test-harness/pull/1043

**Comment by timja** [comment]
included https://github.com/jenkinsci/acceptance-test-harness/pull/1043  in this PR to unblock testing

**Comment by timja** [comment]
ATH passed

**Pull request closed without merging**
