### PR TITLE
[JENKINS-44508] git-userContent ATH test is failing

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
[JENKINS-44508](https://issues.jenkins-ci.org/browse/JENKINS-44508)

Set user.name and user.email before trying to commit

@reviewbybees specially @varyvol

### CODE REVIEW

**Comment by varyvol** [comment]
🐝 providing the build is successful.

**Comment by raul-arabaolaza** [comment]
Please note that the failure in the PR Builder is not related. However it seems that there are a lot of missing tests on the build. Maybe the PR Builder is not in good shape.

**Comment by raul-arabaolaza** [comment]
@andresrc Like your idea, will change the code

**Comment by raul-arabaolaza** [comment]
@andresrc at the end setting the proper escaping for your idea makes the code not very readable, so I will stick with the initial proposal

**Comment by raul-arabaolaza** [comment]
Please also note that by no setting the `--global` flag this change is setting the `user.name` and `user.email`only on the current repo, no globally. See [this article](https://help.github.com/articles/setting-your-username-in-git/)

**Comment by raul-arabaolaza** [comment]
@reviewbybees done

**Pull request merged**
