### PR TITLE
Docker fixtures update to 1.11

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
To pick https://github.com/jenkinsci/docker-fixtures/pull/32 basically.So I can use docker-compose to launch the ATH in a trivially portable way.

This pr should be enough to test the change, I have manually tested this and on my personal CI system

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
```
There are 0 new tests failing, 70 existing failing and 72 skipped.
```

It is a bit dificult to compare with `master` build as it doe snot seem to have coherent results, I will compare with other PRs

**Comment by raul-arabaolaza** [comment]
This is what I am gonna do to properly check this.

* I will remove the dependency update and let the pr builder to run with just the README update this will give me an accurate baseline
* Then I will add again the dependency update and compare the results with the previous execution
* After that thoughts and prayers :grin:

**Comment by raul-arabaolaza** [comment]
Ok, so https://ci.jenkins.io/job/Core/job/acceptance-test-harness/view/change-requests/job/PR-655/ should be my baseline once it finishes

**Comment by raul-arabaolaza** [comment]
Using https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-655/3/tests as baseline, I have restored the fixtures update, will see

**Comment by raul-arabaolaza** [comment]
OK, almost same results but one test failing building docker images, does not seem related, so I will retrigger

**Comment by raul-arabaolaza** [comment]
Retriggering solved the unexpected failures but gave a different number of tests, at this point I am convinced I am suffering flakiness and none of the failures are related to my change

**Review by timja — APPROVED** [review]

**Review by imonteroperez — APPROVED** [review]

**Pull request merged**
