### PR TITLE
Make HttpURLConnection timeouts configurable.

### PR DESCRIPTION
**Pull request by agentgonzo**
The default timeouts may not be for everyone

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
This is really just because Jenkins may not start up in the default timeout.
Whilst making this configurable is OK, I think the startup timeout for Jenkins should be different to anything else.  The init method should probably use something other than `getVersion()` to check that the system is a Jenkins (and possibly poll)

```
openConnection:60, IOUtil (org.jenkinsci.test.acceptance.utils)
getVersion:70, Jenkins (org.jenkinsci.test.acceptance.po)
<init>:38, Jenkins (org.jenkinsci.test.acceptance.po)
<init>:50, Jenkins (org.jenkinsci.test.acceptance.po)
createJenkins:261, FallbackConfig (org.jenkinsci.test.acceptance)
```

**Comment by agentgonzo** [comment]
@jtnord - the startup timeout has been subsequently done in #442. I'll leave this here because I don't think it makes things any worse

**Comment by olivergondza** [comment]
I prefer to do this through a system property. I do not like the aspect how one test can change this and modify the environment for other tests.

**Comment by agentgonzo** [comment]
Sounds reasonable

**Pull request closed without merging**
